import type { Metadata } from "next";
import { Lato, Noto_Sans } from "next/font/google";
import "./globals.css";

const lato = Lato({
  variable: "--font-import-lato",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

const notoSans = Noto_Sans({
  variable: "--font-import-noto",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lato.variable} ${notoSans.variable} font-noto`}>
      <body>{children}</body>
    </html>
  );
}
